[metadata]
name = pyCBS
description = Python-based Complete Basis Set extrapolation framework
author = fab
author_email = delgadoalpizarf@gmail.com
license = MIT
license_files = LICENSE.txt
long_description = file: README.md
long_description_content_type = text/markdown
platforms = any

classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python :: 3

[options]
zip_safe = False
package_dir =
    = src
packages = find:
include_package_data = True
python_requires = >=3.8

install_requires =
    pyscf >= 1.7
    scipy >= 1.5
    numpy >= 1.19

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    pycbs = pycbs.PYCBS:main

[options.extras_require]
testing =
    setuptools
    pytest
    pytest-cov

[tool:pytest]
addopts =
    --cov pycbs --cov-report term-missing
    --verbose
norecursedirs =
    dist
    build
    .tox
testpaths = tests

[flake8]
max_line_length = 88
extend_ignore = E203, W503
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py

[pyscaffold]
version = 4.6
package = pycbs
extensions =
    dsproject
    no_skeleton
    pre_commit
