[metadata]
name = pyCBS
version = 0.1.0
description = Python-based Complete Basis Set extrapolation framework
long_description = file: README.md
long_description_content_type = text/markdown
author = Alberto Guerra-Barroso, Fabio J. Delgado-Alpízar, Antonio J. C. Varandas
license = MIT
license_files = LICENSE.txt
platforms = any

classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only

[options]
zip_safe = False
package_dir =
    = src
packages = find:
include_package_data = True
python_requires = >=3.8

install_requires =
    pyscf >= 1.7
    numpy >= 1.19
    scipy >= 1.5

[options.packages.find]
where = src
exclude =
    tests

[options.entry_points]
console_scripts =
    pycbs = PYCBS:main

[options.extras_require]
testing =
    pytest
    pytest-cov

[tool:pytest]
addopts =
    --cov pycbs --cov-report term-missing
    --verbose
testpaths = tests

[flake8]
max_line_length = 88
extend_ignore = E203, W503
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py
